// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api-reference/authentication.mdx": () => import("../content/docs/api-reference/authentication.mdx?collection=docs"), "api-reference/devices.mdx": () => import("../content/docs/api-reference/devices.mdx?collection=docs"), "api-reference/talkgroups.mdx": () => import("../content/docs/api-reference/talkgroups.mdx?collection=docs"), "api-reference/websocket-protocol.mdx": () => import("../content/docs/api-reference/websocket-protocol.mdx?collection=docs"), "architecture/floor-control.mdx": () => import("../content/docs/architecture/floor-control.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "architecture/key-management.mdx": () => import("../content/docs/architecture/key-management.mdx?collection=docs"), "architecture/satellite-constraints.mdx": () => import("../content/docs/architecture/satellite-constraints.mdx?collection=docs"), "guides/architecture.mdx": () => import("../content/docs/guides/architecture.mdx?collection=docs"), "guides/mobile-setup.mdx": () => import("../content/docs/guides/mobile-setup.mdx?collection=docs"), "guides/ui-development.mdx": () => import("../content/docs/guides/ui-development.mdx?collection=docs"), "infra/local-dev-bootstrap.mdx": () => import("../content/docs/infra/local-dev-bootstrap.mdx?collection=docs"), "infrastructure/database-schema.mdx": () => import("../content/docs/infrastructure/database-schema.mdx?collection=docs"), "infrastructure/deployment.mdx": () => import("../content/docs/infrastructure/deployment.mdx?collection=docs"), "infrastructure/environment.mdx": () => import("../content/docs/infrastructure/environment.mdx?collection=docs"), "runbook/deployment.mdx": () => import("../content/docs/runbook/deployment.mdx?collection=docs"), "runbook/local-development.mdx": () => import("../content/docs/runbook/local-development.mdx?collection=docs"), "runbook/troubleshooting.mdx": () => import("../content/docs/runbook/troubleshooting.mdx?collection=docs"), "stack-and-tradeoffs/backend.mdx": () => import("../content/docs/stack-and-tradeoffs/backend.mdx?collection=docs"), "stack-and-tradeoffs/infrastructure.mdx": () => import("../content/docs/stack-and-tradeoffs/infrastructure.mdx?collection=docs"), "stack-and-tradeoffs/mobile.mdx": () => import("../content/docs/stack-and-tradeoffs/mobile.mdx?collection=docs"), "stack-and-tradeoffs/transport.mdx": () => import("../content/docs/stack-and-tradeoffs/transport.mdx?collection=docs"), "ui-ux/design-philosophy.mdx": () => import("../content/docs/ui-ux/design-philosophy.mdx?collection=docs"), "ui-ux/mobile-app-ux.mdx": () => import("../content/docs/ui-ux/mobile-app-ux.mdx?collection=docs"), "ui-ux/web-portal-ux.mdx": () => import("../content/docs/ui-ux/web-portal-ux.mdx?collection=docs"), }),
};
export default browserCollections;