import { ActivityEvent, Channel, Device, KeyGroup, Router, Transmission, User } from './types';

export const keyGroups: KeyGroup[] = [
  { id: 'kg-core', name: 'Core Command', algorithm: 'AES-256-GCM', rotationDays: 30 },
  { id: 'kg-field', name: 'Field Ops', algorithm: 'AES-256-GCM', rotationDays: 14 },
  { id: 'kg-med', name: 'Medical Response', algorithm: 'ChaCha20-Poly1305', rotationDays: 7 },
  { id: 'kg-log', name: 'Logistics', algorithm: 'AES-192-GCM', rotationDays: 21 },
];

export const routers: Router[] = [
  {
    id: 'rtr-nyc-01',
    name: 'NYC-Core-01',
    region: 'North Sector',
    status: 'online',
    signalStrength: 92,
    assignedChannels: ['ch-alpha', 'ch-ops', 'ch-med'],
    connectedDeviceIds: ['dev-001', 'dev-002', 'dev-006'],
    lastHeartbeat: '2026-03-03T13:22:17Z',
  },
  {
    id: 'rtr-nyc-02',
    name: 'NYC-East-02',
    region: 'East Sector',
    status: 'degraded',
    signalStrength: 71,
    assignedChannels: ['ch-alpha', 'ch-log'],
    connectedDeviceIds: ['dev-003', 'dev-004'],
    lastHeartbeat: '2026-03-03T13:22:02Z',
  },
  {
    id: 'rtr-nyc-03',
    name: 'NYC-West-03',
    region: 'West Sector',
    status: 'online',
    signalStrength: 85,
    assignedChannels: ['ch-ops', 'ch-evac'],
    connectedDeviceIds: ['dev-005', 'dev-007', 'dev-008'],
    lastHeartbeat: '2026-03-03T13:22:29Z',
  },
  {
    id: 'rtr-nyc-04',
    name: 'NYC-South-04',
    region: 'South Sector',
    status: 'offline',
    signalStrength: 0,
    assignedChannels: ['ch-log'],
    connectedDeviceIds: ['dev-009'],
    lastHeartbeat: '2026-03-03T12:56:04Z',
  },
];

export const devices: Device[] = [
  {
    id: 'dev-001',
    label: 'Unit 1A',
    routerId: 'rtr-nyc-01',
    status: 'online',
    signalStrength: 89,
    battery: 94,
    assignedTalkgroup: 'Alpha Dispatch',
    lastGps: '40.7414,-73.9897',
    firmware: 'v3.8.2',
  },
  {
    id: 'dev-002',
    label: 'Unit 2B',
    routerId: 'rtr-nyc-01',
    status: 'online',
    signalStrength: 83,
    battery: 68,
    assignedTalkgroup: 'Operations',
    lastGps: '40.7442,-73.9808',
    firmware: 'v3.8.2',
  },
  {
    id: 'dev-003',
    label: 'Unit 3C',
    routerId: 'rtr-nyc-02',
    status: 'degraded',
    signalStrength: 58,
    battery: 53,
    assignedTalkgroup: 'Logistics',
    lastGps: '40.7273,-73.9822',
    firmware: 'v3.7.9',
  },
  {
    id: 'dev-004',
    label: 'Unit 4D',
    routerId: 'rtr-nyc-02',
    status: 'online',
    signalStrength: 76,
    battery: 44,
    assignedTalkgroup: 'Alpha Dispatch',
    lastGps: '40.7322,-73.9768',
    firmware: 'v3.8.2',
  },
  {
    id: 'dev-005',
    label: 'Unit 5E',
    routerId: 'rtr-nyc-03',
    status: 'online',
    signalStrength: 81,
    battery: 87,
    assignedTalkgroup: 'Operations',
    lastGps: '40.7291,-74.0021',
    firmware: 'v3.8.2',
  },
  {
    id: 'dev-006',
    label: 'Unit 6F',
    routerId: 'rtr-nyc-01',
    status: 'online',
    signalStrength: 91,
    battery: 98,
    assignedTalkgroup: 'Medical',
    lastGps: '40.7461,-73.9924',
    firmware: 'v3.8.3',
  },
  {
    id: 'dev-007',
    label: 'Unit 7G',
    routerId: 'rtr-nyc-03',
    status: 'degraded',
    signalStrength: 62,
    battery: 36,
    assignedTalkgroup: 'Evacuation',
    lastGps: '40.7218,-74.0128',
    firmware: 'v3.7.8',
  },
  {
    id: 'dev-008',
    label: 'Unit 8H',
    routerId: 'rtr-nyc-03',
    status: 'online',
    signalStrength: 79,
    battery: 73,
    assignedTalkgroup: 'Operations',
    lastGps: '40.7348,-74.0042',
    firmware: 'v3.8.1',
  },
  {
    id: 'dev-009',
    label: 'Unit 9I',
    routerId: 'rtr-nyc-04',
    status: 'offline',
    signalStrength: 0,
    battery: 12,
    assignedTalkgroup: 'Logistics',
    lastGps: '40.7068,-74.0134',
    firmware: 'v3.6.4',
  },
];

export const channels: Channel[] = [
  {
    id: 'ch-alpha',
    name: 'Alpha Dispatch',
    activeTransmission: true,
    transmittingUserId: 'usr-001',
    assignedRouterIds: ['rtr-nyc-01', 'rtr-nyc-02'],
    encrypted: true,
    locked: false,
    muted: false,
  },
  {
    id: 'ch-ops',
    name: 'Operations',
    activeTransmission: true,
    transmittingUserId: 'usr-002',
    assignedRouterIds: ['rtr-nyc-01', 'rtr-nyc-03'],
    encrypted: true,
    locked: false,
    muted: false,
  },
  {
    id: 'ch-med',
    name: 'Medical',
    activeTransmission: false,
    transmittingUserId: null,
    assignedRouterIds: ['rtr-nyc-01'],
    encrypted: true,
    locked: false,
    muted: false,
  },
  {
    id: 'ch-log',
    name: 'Logistics',
    activeTransmission: false,
    transmittingUserId: null,
    assignedRouterIds: ['rtr-nyc-02', 'rtr-nyc-04'],
    encrypted: false,
    locked: true,
    muted: false,
  },
  {
    id: 'ch-evac',
    name: 'Evacuation',
    activeTransmission: true,
    transmittingUserId: 'usr-004',
    assignedRouterIds: ['rtr-nyc-03'],
    encrypted: true,
    locked: false,
    muted: true,
  },
];

export const users: User[] = [
  {
    id: 'usr-001',
    displayName: 'A. Navarro',
    assignedDeviceId: 'dev-001',
    activeChannelId: 'ch-alpha',
    role: 'dispatcher',
    keyGroupId: 'kg-core',
    status: 'online',
    suspended: false,
  },
  {
    id: 'usr-002',
    displayName: 'M. Singh',
    assignedDeviceId: 'dev-002',
    activeChannelId: 'ch-ops',
    role: 'operator',
    keyGroupId: 'kg-field',
    status: 'online',
    suspended: false,
  },
  {
    id: 'usr-003',
    displayName: 'D. Allen',
    assignedDeviceId: 'dev-003',
    activeChannelId: 'ch-log',
    role: 'field',
    keyGroupId: 'kg-log',
    status: 'degraded',
    suspended: false,
  },
  {
    id: 'usr-004',
    displayName: 'R. Kim',
    assignedDeviceId: 'dev-007',
    activeChannelId: 'ch-evac',
    role: 'admin',
    keyGroupId: 'kg-core',
    status: 'online',
    suspended: false,
  },
  {
    id: 'usr-005',
    displayName: 'L. Ortega',
    assignedDeviceId: null,
    activeChannelId: null,
    role: 'operator',
    keyGroupId: 'kg-med',
    status: 'offline',
    suspended: true,
  },
];

export const transmissions: Transmission[] = [
  {
    id: 'tx-1001',
    channelId: 'ch-alpha',
    userId: 'usr-001',
    startedAt: '2026-03-03T13:19:20Z',
    durationSec: 96,
    sourceRouterId: 'rtr-nyc-01',
  },
  {
    id: 'tx-1002',
    channelId: 'ch-ops',
    userId: 'usr-002',
    startedAt: '2026-03-03T13:20:51Z',
    durationSec: 62,
    sourceRouterId: 'rtr-nyc-03',
  },
  {
    id: 'tx-1003',
    channelId: 'ch-evac',
    userId: 'usr-004',
    startedAt: '2026-03-03T13:21:45Z',
    durationSec: 44,
    sourceRouterId: 'rtr-nyc-03',
  },
];

export const activities: ActivityEvent[] = [
  {
    id: 'act-1',
    timestamp: '13:22:29',
    severity: 'info',
    message: 'NYC-West-03 applied channel priority update for Evacuation.',
  },
  {
    id: 'act-2',
    timestamp: '13:21:12',
    severity: 'warning',
    message: 'Unit 7G battery dropped below 40 percent.',
  },
  {
    id: 'act-3',
    timestamp: '13:19:54',
    severity: 'critical',
    message: 'NYC-South-04 heartbeat timeout exceeded threshold.',
  },
  {
    id: 'act-4',
    timestamp: '13:18:08',
    severity: 'info',
    message: 'Dispatcher A. Navarro created temporary channel Bravo-Temp.',
  },
  {
    id: 'act-5',
    timestamp: '13:16:41',
    severity: 'warning',
    message: 'Logistics channel remains locked after policy sync.',
  },
];
